# Copyright (c) David Hubbard 2016. Licensed under the GPLv3.
include $(TOP)lib/make/head.inc

TARGET_LIB=liblanguage.a
PKGCONFIG_PKGS+=vulkan
SRCS=language.cpp VkEnum.cpp
HDRS=VkPtr.h VkInit.h VkEnum.h

include $(TOP)lib/make/tail.inc
